### ISSUE TITLE
The WEBUI is not working anymore

### ISSUE THREAD

**Issue by AlessandroMondin00** [UX-Decoder/Semantic-SAM#34]
I tried to use your webui but it is not working.<br>
<img width="1376" alt="Screenshot 2023-07-24 at 17 40 20" src="https://github.com/UX-Decoder/Semantic-SAM/assets/129836202/65ece418-10e5-4032-abcf-dab43f5d47fb"> <br>

Is it something temporal or was it shut-down?

**Comment by lonelyqian** [comment]
same error bro. Just hope they can fix it out quickly

**Comment by FengLi-ust** [comment]
We have fixed it. Thank you.

**Comment by AlessandroMondin00** [comment]
Hello, this functionality is still not working for me. <br>
<img width="843" alt="Screenshot 2023-07-25 at 10 58 37" src="https://github.com/UX-Decoder/Semantic-SAM/assets/129836202/0efa4652-8376-4c52-898d-99e33caedbd0">  <br>
<img width="1428" alt="Screenshot 2023-07-25 at 10 58 00" src="https://github.com/UX-Decoder/Semantic-SAM/assets/129836202/0038d771-f36f-4753-b1d1-29612a68766b">

**Comment by FengLi-ust** [comment]
Not sure about the reason. You can try to run the demo locally. We will fix this issue ASAP. Thanks.

**Comment by FengLi-ust** [comment]
I think it is working now.

**Comment by AlessandroMondin00** [comment]
Works the webpage but I am not receiving masks.
<img width="1295" alt="Screenshot 2023-07-25 at 12 14 15" src="https://github.com/UX-Decoder/Semantic-SAM/assets/129836202/e494b97b-3077-4626-b78e-1f58272bd4dc">
I opened an [issue](https://github.com/UX-Decoder/Semantic-SAM/issues/33) here regarding my problem with the demo locally (I don't have cuda)

**Comment by FengLi-ust** [comment]
Seems the server network has some issues. You can try the demo locally if possible.
